config/routes.rb
Rails.application.routes.draw do
  resources :lessons

  root 'lessons#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :content, :presence => true

  has_attached_file :attachment,
      :path => ":rails_root/public/:class/:attachment/:id/:style_:basename.:extension",
      :url => ":class/:attachment/:id/:style_:basename.:extension"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :lesson

  validates :title, :presence => true

  has_attached_file :attachment,
      :path => ":rails_root/public/:class/:attachment/:id/:style_:basename.:extension",
      :url => ":class/:attachment/:id/:style_:basename.:extension"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :documents, dependent: :destroy
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :documents, :questions, :allow_destroy => true

  validates :name, :category, :level, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :lesson

  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, :allow_destroy => true

  validates :name, :content, :presence => true

  has_attached_file :attachment,
      :path => ":rails_root/public/:class/:attachment/:id/:style_:basename.:extension",
      :url => ":class/:attachment/:id/:style_:basename.:extension"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @lesson.documents.build
    @question = @lesson.questions.build
    @question.answers.build
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :category, :level, :documents_attributes => [:id, :lesson_id, :title, :attachment, :_destroy], :questions_attributes => [:id, :lessond_id, :name, :content, :_destroy, :answers_attributes => [:id, :question_id, :correct_answer, :content, :_destroy]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails4 Nested Form" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Lessons", lessons_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lessons/_form.html.erb
<%= nested_form_for @lesson, :html => { :class => "form-horizontal lesson" } do |f| %>

  <% if @lesson.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @lesson.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :level, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :level, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2"></label>
    <div class="col-lg-10">
      <h2>Documents</h2>

      <div id="lesson_documents">
        <%= f.fields_for :documents do |d_form| %>
          <div class="form-group">
            <%= f.label :title, :class => 'control-label col-lg-2' %>
            <div class="col-lg-10">
              <%= d_form.text_field :title, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :attachment, :class => 'control-label col-lg-2' %>
            <div class="col-lg-10">
              <%= d_form.file_field :attachment %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
              <%= d_form.link_to_remove "Remove this document", :class => 'btn btn-danger btn-sm' %>
            </div>
          </div>
          <hr />
        <% end %>
      </div>
      <div class="form-group">
        <div class="col-lg-10">
          <%= f.link_to_add "Add a document", :documents, :data => { :target => "#lesson_documents" }, :class => 'btn btn-primary btn-sm' %>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2"></label>
    <div class="col-lg-10">
      <h2>Questions</h2>

      <div id="lesson_questions">
        <%= f.fields_for :questions do |q_form| %>
          <div class="form-group">
            <%= f.label :name, :class => 'control-label col-lg-2' %>
            <div class="col-lg-10">
              <%= q_form.text_field :name, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :content, :class => 'control-label col-lg-2' %>
            <div class="col-lg-10">
              <%= q_form.text_field :content, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :attachment, :class => 'control-label col-lg-2' %>
            <div class="col-lg-10">
              <%= q_form.file_field :attachment %>
            </div>
          </div>
          <hr />
          <div class="form-group">
            <label class="control-label col-lg-2"></label>
            <div class="col-lg-10">
              <h2>Answers</h2>
              <div id="question_answers_<%= q_form.options[:child_index] %>">
                <%= q_form.fields_for :answers do |a_form| %>
                  <div class="form-group">
                    <label class="control-label col-lg-2"><%= a_form.check_box :correct_answer %></label>
                    <div class="col-lg-10">
                      <%= f.label :correct_answer %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :content, :class => 'control-label col-lg-2' %>
                    <div class="col-lg-10">
                      <%= a_form.text_field :content, :class => 'form-control' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :attachment, :class => 'control-label col-lg-2' %>
                    <div class="col-lg-10">
                      <%= a_form.file_field :attachment %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <%= a_form.link_to_remove "Remove", :class => 'btn btn-danger btn-sm' %>
                    </div>
                  </div>
                  <hr />
                <% end %>
              </div>
              <div class="form-group">
                <div class="col-lg-10">
                  <%= q_form.link_to_add "Add an answer", :answers, :data => { :target => "#question_answers_#{q_form.options[:child_index]}" }, :class => 'btn btn-primary btn-sm' %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
              <%= q_form.link_to_remove "Remove", :class => 'btn btn-danger' %>
            </div>
          </div>
          <hr />
        <% end %>
      </div>
      <div class="form-group">
        <div class="col-lg-10">
          <%= f.link_to_add "Add a question", :questions, :data => { :target => "#lesson_questions" }, :class => 'btn btn-primary btn-sm' %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lessons_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/lessons/edit.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lessons/index.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to lesson.id, lesson_path(lesson) %></td>
        <td><%= lesson.name %></td>
        <td><%= lesson.category %></td>
        <td><%= lesson.level %></td>
        <td><%=l lesson.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      lesson_path(lesson), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lesson_path(lesson), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lesson_path(lesson),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lesson_path,
            :class => 'btn btn-primary' %>

app/views/lessons/new.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lessons/show.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @lesson.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @lesson.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @lesson.level %></dd>

  <h3>Documents</h3>
  <div class="row">
    <% @lesson.documents.each do |d| %>
      <div class="span3"><%= d.title %></div>
      <div class="span4"><%= link_to "click here to download", d.attachment.url, :target => "_blank" %></div>
    <% end %>
  </div>
  <h3>Questions</h3>
  <table width="100%">
    <% @lesson.questions.each_with_index do |q, i| %>
      <tr>
        <td colspan="2"><%= i+1 %>. <%= q.content %></td>
      </tr>
      <tr>
        <td width="2%"></td>
        <td width="98%">
          <table>
            <% q.answers.each_with_index do |a, i| %>
              <tr>
                <td><%= i+1 %>. <%= a.content %>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
      <tr><td colspan="2">&nbsp;</td></tr>
    <% end %>
  </table>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lessons_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lesson_path(@lesson), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lesson_path(@lesson),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>